### ISSUE TITLE
`;parsemembers` Rework

### ISSUE THREAD

**Issue by Ragviswa** [Thomasc33/ViBot#552]
### Problems, Frustrations, General Description
`;parsemembers` is an old command written ~3 years ago. This means that the original intent of the command has been modified over time, it uses older programming practices, and some parts of the code are completely unused. In addition, there are now additional features that need to be added on top of it which is difficult to integrate due to the bloated and messy nature of the command.
### Improvements, Additions, Changes
`;parsemembers` will be written from the ground up, keeping whatever features are necessary, adding any new features and improving the quality of life wherever possible. The exact changes are unclear, so will need to be investigated and scoped out with Officer teams.
### Phases of the rework
The rework of the parse will happen in a couple of phases, in order to break up the work into manageable sections with realistic time-frames for completion. Currently the plan is as follows:
#### Phase 1
- port `parsemembers.js` to `parse.js` and add slash command version with subcommands. Options available are `members`, `reacts`, and `basic`
- improve the name matching behavior, as described by husky's comment below
- See #707 for a more detailed explanation
#### Phase 2
- Realmeye integration for guild leaks (could also be used for gear parse, but that is secondary)
- Automatic name changes
- Separate parse logging into a separate command (pending officer discussion on parsing)
#### Phase 3
- Leaker tracking through db correlations
- Switch to tesseract OCR because google is stinky
#### Phase 4
- website parse???
- ascend to godhood, striking down the mere mortals who dare to break the sacred `raiding-rules`

### Possible List of Changes:
- [ ] Improving Embed Formatting
- [ ] Ensuring all parse embed fields are necessary
- [ ] pre-processing improvements for OCR
- [ ] Having better matching on names for parsing (l's, i's and whitespace)
- [ ] Reconnecting set parsing using RealmEye
- [ ] Guild leaks via Realmeye
- [ ] Crasher/Leaker correlations from parse logs
- [ ] Automatic name changes via Realmeye

### Current List of Changes:
- [ ] Fixing all ESLint Flagged Errors
- [x] #551
- [x] #550
- [x] #657
- [x] #658 
- [x] #662
- [x] #705
- [x] #706
- [ ] #707

### Paths to Files
- [/commands/parsemembers.js](https://github.com/ViBotTeam/ViBot/blob/master/commands/parsemembers.js)
- [/commands/afkCheck.js](https://github.com/ViBotTeam/ViBot/blob/master/commands/afkCheck.js)
- [/commands/parse,js](https://github.com/ViBotTeam/ViBot/blob/test-parse-changes/commands/parse.js)
- [/data/quotas.json](https://github.com/ViBotTeam/ViBot/blob/master/data/quotas.json)
- [/data/currentweekInfo.json](https://github.com/ViBotTeam/ViBot/blob/master/data/currentweekInfo.json)
