### ISSUE TITLE
`;request` on `;afk` does not work

### ISSUE THREAD

**Issue by Ragviswa** [Thomasc33/ViBot#586]
### Problems, Frustrations, General Description
`;request` on `;afk` is not built ideally for integration and at the moment does not work. The way it adds a button is to copy an existing button and change the name, but this does not make it scalable for more than one `;request` on an existing `;afk`.
### How to Reproduce
Run the `;request` command after putting up an `;afk` or joining a run.
### Improvements, Additions, Changes
`;request` should be restructured such that the command can be run on multiple times on an existing `;afk`. It should work smoothly on existing runs.
## Tasks
- [x] Identify the exact cause of `;request` not working
- [x] Restructure `;request` to be better for `;afk`
- [x] Test to ensure the change works as intended
### Paths to Files
- [/commands/afkCheck.js](../blob/master/commands/afkCheck.js)
- [/commands/afkTemplate.js](../blob/master/commands/afkTemplate.js)
- [/commands/request.js](../blob/master/commands/request.js)
### Screenshots of Bug, Examples for Features
<img width="584" alt="Screenshot 2023-11-10 at 17 02 59" src="https://github.com/ViBotTeam/ViBot/assets/59955668/b0b74095-dbe5-4e08-9656-6f53a9931a1a">
